set_property SRC_FILE_INFO {cfile:/home/innovril/digital_logic_lab/run_vivido/3_edge_t_flipflop/edge_t_flipflop.xdc rfile:../../../../edge_t_flipflop.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC19 [get_ports clk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AC21 [get_ports sw1_t]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F8 [get_ports led8_Q]
