set_property PACKAGE_PIN AC19 [get_ports clk]
set_property PACKAGE_PIN Y3 [get_ports reset]
set_property PACKAGE_PIN AC21 [get_ports set]

set_property PACKAGE_PIN W8 [get_ports key_row2]
set_property PACKAGE_PIN Y7 [get_ports key_row3]
set_property PACKAGE_PIN AA8 [get_ports key_row4]
set_property PACKAGE_PIN V8 [get_ports key_col1]
set_property PACKAGE_PIN V9 [get_ports key_col2]

set_property PACKAGE_PIN D26 [get_ports {num0_scan_select[5]}]
set_property PACKAGE_PIN E25 [get_ports {num0_scan_select[4]}]
set_property PACKAGE_PIN E26 [get_ports {num0_scan_select[3]}]
set_property PACKAGE_PIN G25 [get_ports {num0_scan_select[2]}]
set_property PACKAGE_PIN G26 [get_ports {num0_scan_select[1]}]
set_property PACKAGE_PIN H26 [get_ports {num0_scan_select[0]}]

set_property PACKAGE_PIN A2 [get_ports {num0_seg7[6]}]
set_property PACKAGE_PIN D4 [get_ports {num0_seg7[5]}]
set_property PACKAGE_PIN E5 [get_ports {num0_seg7[4]}]
set_property PACKAGE_PIN B4 [get_ports {num0_seg7[3]}]
set_property PACKAGE_PIN B2 [get_ports {num0_seg7[2]}]
set_property PACKAGE_PIN E6 [get_ports {num0_seg7[1]}]
set_property PACKAGE_PIN C3 [get_ports {num0_seg7[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {num0_scan_select[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num0_scan_select[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num0_scan_select[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num0_scan_select[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num0_scan_select[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num0_scan_select[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num0_seg7[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num0_seg7[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num0_seg7[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num0_seg7[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num0_seg7[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num0_seg7[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num0_seg7[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports key_col1]
set_property IOSTANDARD LVCMOS33 [get_ports key_col2]
set_property IOSTANDARD LVCMOS33 [get_ports key_row2]
set_property IOSTANDARD LVCMOS33 [get_ports key_row4]
set_property IOSTANDARD LVCMOS33 [get_ports key_row3]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports set]
