set_property PACKAGE_PIN AC22 [get_ports Sw3_A2]
set_property PACKAGE_PIN AD24 [get_ports Sw2_A1]
set_property PACKAGE_PIN AC21 [get_ports Sw1_A0]

set_property PACKAGE_PIN H7 [get_ports LED1_Y0]
set_property PACKAGE_PIN D5 [get_ports LED2_Y1]
set_property PACKAGE_PIN A3 [get_ports LED3_Y2]
set_property PACKAGE_PIN A5 [get_ports LED4_Y3]
set_property PACKAGE_PIN A4 [get_ports LED5_Y4]
set_property PACKAGE_PIN F7 [get_ports LED6_Y5]
set_property PACKAGE_PIN G8 [get_ports LED7_Y6]
set_property PACKAGE_PIN H8 [get_ports LED8_Y7]

set_property IOSTANDARD LVCMOS33 [get_ports LED1_Y0]
set_property IOSTANDARD LVCMOS33 [get_ports LED2_Y1]
set_property IOSTANDARD LVCMOS33 [get_ports LED3_Y2]
set_property IOSTANDARD LVCMOS33 [get_ports LED4_Y3]
set_property IOSTANDARD LVCMOS33 [get_ports LED5_Y4]
set_property IOSTANDARD LVCMOS33 [get_ports LED6_Y5]
set_property IOSTANDARD LVCMOS33 [get_ports LED7_Y6]
set_property IOSTANDARD LVCMOS33 [get_ports LED8_Y7]
set_property IOSTANDARD LVCMOS33 [get_ports Sw1_A0]
set_property IOSTANDARD LVCMOS33 [get_ports Sw2_A1]
set_property IOSTANDARD LVCMOS33 [get_ports Sw3_A2]
